# Generated by Django 5.1.1 on 2024-11-01 11:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobData", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StuffingSheetModel",
            fields=[
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="jobData.dataofjob",
                    ),
                ),
                ("jobNumber", models.IntegerField(blank=True, null=True)),
                (
                    "depot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("THAR DRY PORT", "THAR DRY PORT"),
                            ("INLAND CONTAINER DEPOT", "INLAND CONTAINER DEPOT"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "depotAddress",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "A UNIT OF CONTAINER OF INDIA LTD BHAGAT KI KOTHI, JODHPUR",
                                "A UNIT OF CONTAINER OF INDIA LTD BHAGAT KI KOTHI, JODHPUR",
                            ),
                            (
                                "A UNIT OF HASTI PETRO CHEMICAL & SHIPPING LTD",
                                "A UNIT OF HASTI PETRO CHEMICAL & SHIPPING LTD",
                            ),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stuffingType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ICD STUFFING", "ICD STUFFING"),
                            ("FACTORY STUFFING", "FACTORY "),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("bookingNum", models.CharField(blank=True, max_length=255, null=True)),
                ("invoiceNo", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "containerNum",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("shutout", models.IntegerField(blank=True, null=True)),
                (
                    "dateOfStuffing",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                (
                    "shippingLine",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("customSeal", models.IntegerField(blank=True, null=True)),
                ("size_20", models.BooleanField(default=False, verbose_name="size=20")),
                ("size_40", models.BooleanField(default=False, verbose_name="size=40")),
                (
                    "portOfDestination",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shippingLineSeal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "portOfLoading",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("shippingBillNo", models.IntegerField(blank=True, null=True)),
                ("shippingBillDate", models.DateField(blank=True, null=True)),
                (
                    "exporterName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("nameOfGood", models.CharField(blank=True, max_length=255, null=True)),
                ("noOfPkgs", models.IntegerField(blank=True, null=True)),
                ("grossWt", models.FloatField(blank=True, null=True)),
                ("valueINR", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TotalStuffingValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bookingNum",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("totalPkg", models.IntegerField(blank=True, default=0, null=True)),
                ("totalGrossWt", models.FloatField(blank=True, default=0, null=True)),
                ("totalvalueINR", models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
