# Generated by Django 4.2.8 on 2024-04-02 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobData", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StuffingSheetModel",
            fields=[
                (
                    "jobNumber",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="jobData.dataofjob",
                    ),
                ),
                (
                    "depot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Thar", "THAR DRY PORT"),
                            ("Inland", "INLAND CONTAINER DEPOT"),
                        ],
                        default="Thar",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "depotAddress",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "ContainerIndia",
                                "A UNIT OF CONTAINER OF INDIA LTD BHAGAT KI KOTHI, JODHPUR",
                            ),
                            ("Hasti", "A UNIT OF HASTI PETRO CHEMICAL & SHIPPING LTD"),
                        ],
                        default="A UNIT OF HASTI PETRO CHEMICAL & SHIPPING LTD', 'Hasti'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stuffingType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ICD", "ICD Stuffing"),
                            ("Factory", "Factory Stuffing"),
                        ],
                        default="ICD Stuffing",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "bookingNum",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "invoiceNo",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "containerNum",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("shutout", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "dateOfStuffing",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                (
                    "shippingLine",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("customSeal", models.IntegerField(blank=True, default=0, null=True)),
                ("size_20", models.BooleanField(default=False, verbose_name="size=20")),
                ("size_40", models.BooleanField(default=False, verbose_name="size=40")),
                (
                    "portOfDestination",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "shippingLineSeal",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "portOfLoading",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "shippingBillNo",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "shippingBillDate",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                (
                    "exporterName",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "nameOfGood",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("noOfPkgs", models.IntegerField(blank=True, default=0, null=True)),
                ("grossWt", models.FloatField(blank=True, default=0.0, null=True)),
                ("valueINR", models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TotalStuffingValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bookingNum",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("totalPkg", models.IntegerField(blank=True, default=0, null=True)),
                ("totalGrossWt", models.FloatField(blank=True, default=0, null=True)),
                ("totalvalueINR", models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
