# Generated by Django 4.2.8 on 2024-04-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobData", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcdModel",
            fields=[
                (
                    "jobNumber",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="jobData.dataofjob",
                    ),
                ),
                ("bookingNum", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "exporterAddress",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("consignee", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nameOfOceanCarrier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vesselName", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "placeOfReceiptOfGood",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "portOfLoading",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "portOfDischarge",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "placeOfDeliveryWithStateCode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "containerNum",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("customSeal", models.CharField(blank=True, max_length=255, null=True)),
                ("shippingBillNo", models.IntegerField(blank=True, null=True)),
                ("marks", models.CharField(blank=True, max_length=255, null=True)),
                ("noOfPkgs", models.IntegerField(blank=True, null=True)),
                (
                    "fullCommondityDescription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("grossWt", models.FloatField(blank=True, null=True)),
                ("htsCode", models.IntegerField(blank=True, null=True)),
                (
                    "placeOfIssueOfCargo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dateOfIssueOfCargo", models.DateField(blank=True, null=True)),
                (
                    "exporterName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("NameOfAuthorised", models.CharField(blank=True, max_length=255)),
                (
                    "signatureImg",
                    models.ImageField(
                        blank=True, null=True, upload_to="signature_pic/%y"
                    ),
                ),
            ],
        ),
    ]
