# Generated by Django 4.2.8 on 2024-04-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobData", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherModel",
            fields=[
                (
                    "jobNumber",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="jobData.dataofjob",
                    ),
                ),
                (
                    "bookingNum",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("containerNum", models.CharField(blank=True, max_length=255)),
                ("doExpityDate", models.DateField(blank=True, null=True)),
                ("dispatchDate", models.DateField(blank=True, null=True)),
                ("invoiceDate", models.DateField(blank=True, null=True)),
                (
                    "containerMethodType",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Method-1"), ("2", "Method-2")],
                        default="",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "PanNo",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("vessealCutOffDate", models.DateField(blank=True, null=True)),
                ("handoverDate", models.DateField(blank=True, null=True)),
                ("allotmentDate", models.DateField(blank=True, null=True)),
                (
                    "ChaName",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("seaPortInDate", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
