# Generated by Django 5.1.1 on 2024-11-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobData", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherModel",
            fields=[
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="jobData.dataofjob",
                    ),
                ),
                ("jobNumber", models.IntegerField(blank=True, null=True)),
                (
                    "bookingNum",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("containerNum", models.CharField(blank=True, max_length=255)),
                ("doExpityDate", models.DateField(blank=True, null=True)),
                ("dispatchDate", models.DateField(blank=True, null=True)),
                ("invoiceDate", models.DateField(blank=True, null=True)),
                (
                    "containerMethodType",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Method-1"), ("2", "Method-2")],
                        default="",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "PanNo",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("vessealCutOffDate", models.DateField(blank=True, null=True)),
                ("handoverDate", models.DateField(blank=True, null=True)),
                ("allotmentDate", models.DateField(blank=True, null=True)),
                (
                    "ChaName",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("seaPortInDate", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
