# Generated by Django 5.1.1 on 2024-11-01 11:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobData", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VgmModel",
            fields=[
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="jobData.dataofjob",
                    ),
                ),
                ("jobNumber", models.IntegerField(blank=True, null=True)),
                ("exporterName", models.CharField(blank=True, max_length=255)),
                ("exporterAddress", models.CharField(blank=True, max_length=255)),
                ("IEC_no", models.IntegerField(blank=True, null=True)),
                ("NameOfAuthorised", models.CharField(blank=True, max_length=255)),
                ("bookingNum", models.CharField(blank=True, max_length=255)),
                (
                    "DesignationOfAuthorised",
                    models.CharField(blank=True, max_length=255),
                ),
                ("contactDetail", models.IntegerField(blank=True, null=True)),
                ("containerNum", models.CharField(blank=True, max_length=255)),
                ("size_20", models.BooleanField(default=False, verbose_name="size=20")),
                ("size_40", models.BooleanField(default=False, verbose_name="size=40")),
                (
                    "permissibleWeight",
                    models.IntegerField(
                        blank=True,
                        choices=[(32500, "32,500 lbs"), (32450, "32,450 lbs")],
                        null=True,
                    ),
                ),
                (
                    "WeighBridgeRegistration",
                    models.CharField(blank=True, max_length=255),
                ),
                ("WeighBridgeAddress", models.CharField(blank=True, max_length=255)),
                ("emptyContainerMass", models.FloatField(blank=True, null=True)),
                ("goodMass", models.FloatField(blank=True, null=True)),
                ("dateOfWeigh", models.DateField(blank=True, null=True)),
                ("timeofWeigh", models.TimeField(blank=True, null=True)),
                ("cargoWeight", models.IntegerField(blank=True, null=True)),
                ("containerWeight", models.IntegerField(blank=True, null=True)),
                ("verifiedGrossMass", models.FloatField(blank=True, null=True)),
                ("weightmentSlipNum", models.CharField(blank=True, max_length=255)),
                ("unitOfMeasure", models.CharField(blank=True, max_length=255)),
                ("typeOF", models.CharField(blank=True, default="NA", max_length=255)),
                (
                    "ifHazardous",
                    models.CharField(blank=True, default="NA", max_length=255),
                ),
                (
                    "signatureImg",
                    models.ImageField(
                        blank=True, null=True, upload_to="signature_pic/%y"
                    ),
                ),
                ("todayDate", models.DateField(default=datetime.date.today)),
                (
                    "vesselName",
                    models.CharField(
                        blank=True, default="NA", max_length=255, null=True
                    ),
                ),
                (
                    "vcnNo",
                    models.CharField(
                        blank=True, default="NA", max_length=255, null=True
                    ),
                ),
            ],
        ),
    ]
