# Generated by Django 5.1.1 on 2024-11-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobData", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BolModel",
            fields=[
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="jobData.dataofjob",
                    ),
                ),
                ("jobNumber", models.IntegerField(blank=True, null=True)),
                (
                    "exporterName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("exporterAddress", models.CharField(blank=True, max_length=255)),
                ("gstin", models.CharField(blank=True, max_length=255, null=True)),
                ("consignee", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "notifyDelivery",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bookingNum", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "shippingLine",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "armAddress",
                    models.CharField(
                        blank=True,
                        default="48, District Shopping Center underground Saraswati Nagar, Pali Road, Jodhpur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "initialCarriage_mode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "placeOfReceiptOfGood",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vesselName", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "portOfLoading",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "portOfDestination",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "finalDestination",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("marks", models.CharField(blank=True, max_length=255, null=True)),
                ("noOfPkgs", models.IntegerField(blank=True, null=True)),
                ("grossWt", models.FloatField(blank=True, null=True)),
                ("netWt", models.FloatField(blank=True, null=True)),
                ("CBM", models.FloatField(blank=True, null=True)),
                (
                    "descriptionOfGood",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("shippingBillNo", models.IntegerField(blank=True, null=True)),
                ("IECno", models.IntegerField(blank=True, null=True)),
                ("invoiceNo", models.CharField(blank=True, max_length=255, null=True)),
                ("hsCode", models.CharField(blank=True, max_length=255, null=True)),
                ("poCode", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "containerNum",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shippingLineSeal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("customSeal", models.IntegerField(blank=True, null=True)),
                ("freight", models.CharField(blank=True, max_length=255, null=True)),
                ("dateOfIssue", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
