# Generated by Django 5.1.1 on 2024-11-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobData", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataofjob",
            name="index",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
