# Generated by Django 5.1.1 on 2024-11-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobData", "0002_alter_dataofjob_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataofjob",
            name="index",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
